steps:
  - name: "gcr.io/cloud-builders/yarn"
    id: "install"
    args: ["install"]
  - name: "gcr.io/cloud-builders/yarn"
    id: "test"
    args: ["test"]
    env:
      [
        "BUILD_CMD=build",
        "CHARTING_URL=''",
        "FIRESTORE_URL=''",
        "GITHUB_TOKEN=abcd",
        "SRC_PATH=''",
        "TMP_PATH=/tmp",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    id: "decrypt"
    args:
      - kms
      - decrypt
      - --ciphertext-file=keyfile.json.enc
      - --plaintext-file=keyfile.json
      - --location=global
      - --project=bundle-size-tools
      - --keyring=deploy
      - --key=keyfile
  - name: "gcr.io/cloud-builders/yarn"
    waitFor: ["decrypt"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" != "master" ]]; then yarn add serverless && serverless deploy; else exit 0; fi
