service: bundle-size-tracker

provider:
  name: google
  runtime: nodejs8
  project: bundle-size-tools
  credentials: ~/.gcloud/keyfile.json
  memorySize: 1024
  timeout: 180s

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello:
    handler: trackSize
    events:
      - http: path
